return {
    require("lazy.vim-rhubarb"),
    require("lazy.vim-sleuth"),
    require("lazy.vim-tmux-navigator"),
    require("lazy.onedark"),
    require("lazy.lualine"),
    require("lazy.indent-blankline"),
    require("lazy.comment"),
    require("lazy.harpoon"),
    require("lazy.telescope"),
    require("lazy.nvim-tree"),
    require("lazy.nvim-treesitter"),
    require("lazy.nvim-lspconfig"),
    require("lazy.nvim-cmp"),
    require("lazy.gitsigns"),
    require("lazy.obsidian"),
    require("lazy.fugitive"),
    require("lazy.autopairs"),
    require("lazy.diffview"),
    require("lazy.haskell-tools"),
    require("lazy.trouble"),
    require("lazy.undotree"),
    require("lazy.which-key"),
    -- require("lazy.copilot"),
}

